### ISSUE TITLE
Handling references to other objects

### ISSUE THREAD

**Issue by blagae** [weisjohn/mongoose-simple-fixtures#5]
Is there a way to handle references to other seeded data stores without manually specifying the id ?

User.json

    [
    {"username": "admin", "perms": [ {"permission_name": "write_all"} ]}
    ]

Permission.json

    [
    {"name": "write_all", "perm": "write", "url": "*"}
    ]

**Comment by weisjohn** [comment]
@blagae sorry for the extremely late response. There's nothing to support this except using mongoose refs and _ids
